name: 💿 Build-OpenWrt
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: ⏬ 安装依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev zstd curl unzip tree

    - name: ⏬ 下载 ImageBuilder
      run: |
        curl -L -o imagebuilder.tar.zst https://dl.openwrt.ai/releases/25.12/targets/ramips/mt7620/kwrt-imagebuilder-ramips-mt7620.Linux-x86_64.tar.zst
        tar --use-compress-program=unzstd -xvf imagebuilder.tar.zst
        mv istoreos-imagebuilder-* imagebuilder

    - name: SSH connect to Actions
      uses: P3TERX/ssh2actions@main

    - name: 🚀 上传到 Release
      uses: softprops/action-gh-release@v3
      with:
        tag_name: OpenWrt-kwrt-releases
        body: |
          🌐 IP： 10.0.0.1
          
          👤 用户名： root
          
          🔒 密码： root
        files: |
          imagebuilder/bin/targets/ramips/mt7620/*squashfs-sysupgrade.bin
      env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
